# Generated by Django 4.1.2 on 2022-10-31 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("R", models.PositiveSmallIntegerField(verbose_name="Red Space Value")),
                (
                    "G",
                    models.PositiveSmallIntegerField(verbose_name="Green Space Value"),
                ),
                (
                    "B",
                    models.PositiveSmallIntegerField(verbose_name="Blue Space Value"),
                ),
                (
                    "persent",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Persent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="maincategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Main Category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="attributes_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Type")),
                (
                    "main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="label.maincategory",
                        verbose_name="Main Category ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="attributes_color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="label.color",
                        verbose_name="Color",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="label.attributes_type",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="attributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=30, verbose_name="Attributes")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="label.attributes_type",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="attributes_type",
            constraint=models.UniqueConstraint(
                fields=("main", "name"), name="unique type"
            ),
        ),
        migrations.AddConstraint(
            model_name="attributes",
            constraint=models.UniqueConstraint(
                fields=("type", "name"), name="unique attribute"
            ),
        ),
    ]
