# Generated by Django 4.1.2 on 2022-11-03 19:04

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0001_initial"),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                'SELECT "label_attributes"."id", "label_maincategory"."name", "label_attributestype"."name", "label_attributes"."data", "label_maincategory"."name" AS "maincategory", "label_attributestype"."name" AS "attributes" FROM "label_attributes" INNER JOIN "label_attributestype" ON ("label_attributes"."type_id" = "label_attributestype"."id") INNER JOIN "label_maincategory" ON ("label_attributestype"."main_id" = "label_maincategory"."id")',
                "AttributeTable",
                engine="django.db.backends.sqlite3",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "", "AttributeTable", engine="django.db.backends.sqlite3"
            ),
            atomic=False,
        ),
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                'SELECT "label_attributes"."id", "label_attributestype"."main_id", "label_attributes"."type_id", "label_attributes"."data", "label_attributestype"."main_id" AS "maincategory_id", "label_attributes"."type_id" AS "attributes_id" FROM "label_attributes" INNER JOIN "label_attributestype" ON ("label_attributes"."type_id" = "label_attributestype"."id")',
                "AttributeIndexTable",
                engine="django.db.backends.sqlite3",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "", "AttributeIndexTable", engine="django.db.backends.sqlite3"
            ),
            atomic=False,
        ),
    ]
