# Generated by Django 4.1.2 on 2022-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="request_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="requsert-image/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "analysis_state",
                    models.CharField(
                        choices=[
                            ("U", "Undefine"),
                            ("A", "Accepted"),
                            ("P", "Progress"),
                            ("D", "Done"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="Work State",
                    ),
                ),
            ],
        ),
    ]
