# Generated by Django 4.1.2 on 2022-11-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="request_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="requsert-image/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "analysis_state",
                    models.CharField(
                        choices=[
                            ("U", "Undefine"),
                            ("A", "Accepted"),
                            ("P", "Progress"),
                            ("D", "Done"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="Work State",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
